sudo: true
language: haskell

cabal: "3.0"

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:

  # Cabal
  # - ghc: 8.4.4
  - ghc: 8.6.3
    env:
      - SUBPACKAGE="hgeometry-test"

  - ghc: 8.8.1
    env:
      - SUBPACKAGE="hgeometry-test"

  # Stack
  - ghc: 8.4.2
    env:
      - STACK_YAML="$TRAVIS_BUILD_DIR/stack-ghc8.4.yaml"
      - SUBPACKAGE="hgeometry-test"

  - ghc: 8.6.3
    env:
      - STACK_YAML="$TRAVIS_BUILD_DIR/stack-ghc8.6.yaml"
      - SUBPACKAGE="hgeometry-combinatorial"

  - ghc: 8.6.3
    env:
      - STACK_YAML="$TRAVIS_BUILD_DIR/stack-ghc8.6.yaml"
      - SUBPACKAGE="hgeometry-test"

  - ghc: 8.8.1
    env:
      - STACK_YAML="$TRAVIS_BUILD_DIR/stack-ghc8.8.yaml"
      - SUBPACKAGE="hgeometry-test"

install:
  - |
    if [ -z "$STACK_YAML" ]; then
      ghc --version
      cabal --version
      cabal update
      cabal build --enable-tests --enable-benchmarks ${SUBPACKAGE}
    else
      # install stack
      curl -sSL https://get.haskellstack.org/ | sh

      # build project with stack
      stack --version
      stack build --system-ghc --test --bench --no-run-tests  --no-run-benchmarks ${SUBPACKAGE}
    fi

script:
  - |
    if [ -z "$STACK_YAML" ]; then
      cabal test --enable-tests ${SUBPACKAGE}
    else
      stack test --system-ghc ${SUBPACKAGE}
      stack haddock ${SUBPACKAGE}
    fi

notifications:
  email:
    on_success: change
    on_failure: always
